# Make sure ocamlbuild can find opam-managed packages: first run
#
# eval `opam config env`

# Easiest way to build: using ocamlbuild, which in turn uses ocamlfind

.PHONY : all
all : makergame.native lib/libmakergame.o lib/libtestergame.o

test : makergame.native lib/libtestergame.o testall.sh
	./testall.sh

lib/libmakergame.o:
	gcc -c lib/libmakergame.cpp -o lib/libmakergame.o -std=c++11

lib/libtestergame.o:
	gcc -c lib/libtestergame.cpp -o lib/libtestergame.o -std=c++11

makergame.native : src/*.ml src/*.mly src/*.mll clean
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis -cflags -w,+a-4 \
		src/makergame.native

# "make clean" removes all generated files

.PHONY : clean
clean :
	ocamlbuild -clean
	rm -rf vgcore.*
	rm -rf testall.log *.diff makergame scanner.ml parser.ml parser.mli
	rm -rf lib/libmakergame.o
	rm -rf lib/libtestergame.o
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o *.s *.ll *.out *.exe *.err

# More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

OBJS = ast.cmx llast.cmx codegen.cmx parser.cmx scanner.cmx semant.cmx makergame.cmx

makergame : $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o makergame

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
llast.cmo :
llast.cmx :
ast.cmo :
ast.cmx :
codegen.cmo : ast.cmo llast.cmo
codegen.cmx : ast.cmx llast.cmx
makergame.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo llast.cmo
makergame.cmx : semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx llast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
semant.cmo : ast.cmo
semant.cmx : ast.cmx
parser.cmi : ast.cmo
